/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jaydenetheridge
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPanel = new javax.swing.JTabbedPane();
        ViewTour = new javax.swing.JPanel();
        SelectSport = new javax.swing.JLabel();
        SportsComboBox = new javax.swing.JComboBox<>();
        TournamentTree = new javax.swing.JLabel();
        ViewTourButtton = new javax.swing.JButton();
        ViewGame = new javax.swing.JPanel();
        SelectSport1 = new javax.swing.JLabel();
        SportsComboBox1 = new javax.swing.JComboBox<>();
        ViewTourButtton1 = new javax.swing.JButton();
        SelectRoundNumber = new javax.swing.JComboBox<>();
        SelectGameNumber = new javax.swing.JComboBox<>();
        RoundNumber = new javax.swing.JLabel();
        GameNumber = new javax.swing.JLabel();
        ScrollPaneTeam1 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        ScrollPaneTeam2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Team1Label = new javax.swing.JLabel();
        Team2Label = new javax.swing.JLabel();
        EnterResults = new javax.swing.JPanel();
        SelectSport2 = new javax.swing.JLabel();
        SportsComboBox2 = new javax.swing.JComboBox<>();
        EnterResultsButton = new javax.swing.JButton();
        SelectRoundNumber1 = new javax.swing.JComboBox<>();
        SelectGameNumber1 = new javax.swing.JComboBox<>();
        RoundNumber1 = new javax.swing.JLabel();
        GameNumber1 = new javax.swing.JLabel();
        Team1ScrollPane1 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        Team2ScrollPane1 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        Team1Label1 = new javax.swing.JLabel();
        Team2Label1 = new javax.swing.JLabel();
        SetupTour = new javax.swing.JPanel();
        SelectSport3 = new javax.swing.JLabel();
        SportsComboBox3 = new javax.swing.JComboBox<>();
        TournamentTree3 = new javax.swing.JLabel();
        SetupTourButtton = new javax.swing.JButton();
        ClearTourButtton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SelectSport.setText("Select Sports Tournament");

        SportsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Sport", "Football", "Hockey", "Rugby", "Netball" }));
        SportsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SportsComboBoxActionPerformed(evt);
            }
        });

        TournamentTree.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        TournamentTree.setText("Tournament Tree");

        ViewTourButtton.setText("View Tournament");
        ViewTourButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTourButttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewTourLayout = new javax.swing.GroupLayout(ViewTour);
        ViewTour.setLayout(ViewTourLayout);
        ViewTourLayout.setHorizontalGroup(
            ViewTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewTourLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(SelectSport)
                .addGap(30, 30, 30)
                .addGroup(ViewTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewTourButtton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ViewTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TournamentTree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SportsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        ViewTourLayout.setVerticalGroup(
            ViewTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewTourLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(TournamentTree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectSport)
                    .addComponent(SportsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                .addComponent(ViewTourButtton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        TabbedPanel.addTab("View Tournament", ViewTour);

        SelectSport1.setText("Select Sport first then Round Number");

        SportsComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Sport", "Football", "Hockey", "Rugby", "Netball" }));
        SportsComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SportsComboBox1ActionPerformed(evt);
            }
        });

        ViewTourButtton1.setText("View Tournament");
        ViewTourButtton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTourButtton1ActionPerformed(evt);
            }
        });

        SelectRoundNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Round Number", "1", "Semi Finals", "Finals" }));
        SelectRoundNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectRoundNumberActionPerformed(evt);
            }
        });

        SelectGameNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Sport", "Football", "Hockey", "Rugby", "Netball" }));
        SelectGameNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectGameNumberActionPerformed(evt);
            }
        });

        RoundNumber.setText("Round Number");

        GameNumber.setText("Game Number");

        ScrollPaneTeam1.setViewportView(jTextPane2);

        ScrollPaneTeam2.setViewportView(jTextPane1);

        Team1Label.setText("Team 1");

        Team2Label.setText("Team 2");

        javax.swing.GroupLayout ViewGameLayout = new javax.swing.GroupLayout(ViewGame);
        ViewGame.setLayout(ViewGameLayout);
        ViewGameLayout.setHorizontalGroup(
            ViewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewGameLayout.createSequentialGroup()
                .addGroup(ViewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewGameLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(SelectSport1))
                    .addGroup(ViewGameLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(ViewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SportsComboBox1, 0, 138, Short.MAX_VALUE)
                            .addComponent(ViewTourButtton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewGameLayout.createSequentialGroup()
                .addGroup(ViewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewGameLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(RoundNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelectRoundNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(GameNumber))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewGameLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ViewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Team1Label, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Team2Label, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ScrollPaneTeam2)
                    .addComponent(SelectGameNumber, 0, 138, Short.MAX_VALUE)
                    .addComponent(ScrollPaneTeam1))
                .addGap(72, 72, 72))
        );
        ViewGameLayout.setVerticalGroup(
            ViewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewGameLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(SelectSport1)
                .addGap(18, 18, 18)
                .addComponent(SportsComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(ViewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectRoundNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectGameNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoundNumber)
                    .addComponent(GameNumber))
                .addGroup(ViewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewGameLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ScrollPaneTeam1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewGameLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(Team1Label)))
                .addGroup(ViewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewGameLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ScrollPaneTeam2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewGameLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Team2Label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(ViewTourButtton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        TabbedPanel.addTab("View Round/Game", ViewGame);

        SelectSport2.setText("Select Sport first then Round Number");

        SportsComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Sport", "Football", "Hockey", "Rugby", "Netball" }));
        SportsComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SportsComboBox2ActionPerformed(evt);
            }
        });

        EnterResultsButton.setText("Enter Round Results");
        EnterResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterResultsButtonActionPerformed(evt);
            }
        });

        SelectRoundNumber1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Sport", "Football", "Hockey", "Rugby", "Netball" }));
        SelectRoundNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectRoundNumber1ActionPerformed(evt);
            }
        });

        SelectGameNumber1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Sport", "Football", "Hockey", "Rugby", "Netball" }));
        SelectGameNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectGameNumber1ActionPerformed(evt);
            }
        });

        RoundNumber1.setText("Round Number");

        GameNumber1.setText("Game Number");

        Team1ScrollPane1.setViewportView(jTextPane5);

        Team2ScrollPane1.setViewportView(jTextPane6);

        Team1Label1.setText("Team 1");

        Team2Label1.setText("Team 2");

        javax.swing.GroupLayout EnterResultsLayout = new javax.swing.GroupLayout(EnterResults);
        EnterResults.setLayout(EnterResultsLayout);
        EnterResultsLayout.setHorizontalGroup(
            EnterResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterResultsLayout.createSequentialGroup()
                .addGroup(EnterResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EnterResultsLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(SelectSport2))
                    .addGroup(EnterResultsLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(EnterResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SportsComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EnterResultsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterResultsLayout.createSequentialGroup()
                .addGroup(EnterResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EnterResultsLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(RoundNumber1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelectRoundNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(GameNumber1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnterResultsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(EnterResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Team1Label1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Team2Label1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EnterResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Team2ScrollPane1)
                    .addComponent(SelectGameNumber1, 0, 138, Short.MAX_VALUE)
                    .addComponent(Team1ScrollPane1))
                .addGap(72, 72, 72))
        );
        EnterResultsLayout.setVerticalGroup(
            EnterResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterResultsLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(SelectSport2)
                .addGap(18, 18, 18)
                .addComponent(SportsComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(EnterResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectRoundNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectGameNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoundNumber1)
                    .addComponent(GameNumber1))
                .addGroup(EnterResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EnterResultsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Team1ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EnterResultsLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(Team1Label1)))
                .addGroup(EnterResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EnterResultsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Team2ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EnterResultsLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Team2Label1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(EnterResultsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        TabbedPanel.addTab("Enter Round Results", EnterResults);

        SelectSport3.setText("Select Sports Tournament");

        SportsComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Sport", "Football", "Hockey", "Rugby", "Netball" }));
        SportsComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SportsComboBox3ActionPerformed(evt);
            }
        });

        TournamentTree3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        TournamentTree3.setText("Tournament Tree");

        SetupTourButtton.setText("Setup Tournament");
        SetupTourButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetupTourButttonActionPerformed(evt);
            }
        });

        ClearTourButtton.setText("Clear Tournament");
        ClearTourButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearTourButttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SetupTourLayout = new javax.swing.GroupLayout(SetupTour);
        SetupTour.setLayout(SetupTourLayout);
        SetupTourLayout.setHorizontalGroup(
            SetupTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SetupTourLayout.createSequentialGroup()
                .addGroup(SetupTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SetupTourLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(SelectSport3)
                        .addGap(30, 30, 30)
                        .addGroup(SetupTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TournamentTree3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SportsComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(SetupTourLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(SetupTourButtton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(ClearTourButtton)))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        SetupTourLayout.setVerticalGroup(
            SetupTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SetupTourLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(TournamentTree3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SetupTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectSport3)
                    .addComponent(SportsComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, Short.MAX_VALUE)
                .addGroup(SetupTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SetupTourButtton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearTourButtton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        TabbedPanel.addTab("Setup Tournament", SetupTour);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SportsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SportsComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SportsComboBoxActionPerformed

    private void SportsComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SportsComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SportsComboBox1ActionPerformed

    private void ViewTourButtton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTourButtton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewTourButtton1ActionPerformed

    private void SportsComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SportsComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SportsComboBox3ActionPerformed

    private void SetupTourButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetupTourButttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SetupTourButttonActionPerformed

    private void SelectRoundNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectRoundNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectRoundNumberActionPerformed

    private void SelectGameNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectGameNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectGameNumberActionPerformed

    private void SportsComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SportsComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SportsComboBox2ActionPerformed

    private void EnterResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterResultsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterResultsButtonActionPerformed

    private void SelectRoundNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectRoundNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectRoundNumber1ActionPerformed

    private void SelectGameNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectGameNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectGameNumber1ActionPerformed

    private void ClearTourButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearTourButttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearTourButttonActionPerformed

    private void ViewTourButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTourButttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewTourButttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearTourButtton;
    private javax.swing.JPanel EnterResults;
    private javax.swing.JButton EnterResultsButton;
    private javax.swing.JLabel GameNumber;
    private javax.swing.JLabel GameNumber1;
    private javax.swing.JLabel RoundNumber;
    private javax.swing.JLabel RoundNumber1;
    private javax.swing.JScrollPane ScrollPaneTeam1;
    private javax.swing.JScrollPane ScrollPaneTeam2;
    private javax.swing.JComboBox<String> SelectGameNumber;
    private javax.swing.JComboBox<String> SelectGameNumber1;
    private javax.swing.JComboBox<String> SelectRoundNumber;
    private javax.swing.JComboBox<String> SelectRoundNumber1;
    private javax.swing.JLabel SelectSport;
    private javax.swing.JLabel SelectSport1;
    private javax.swing.JLabel SelectSport2;
    private javax.swing.JLabel SelectSport3;
    private javax.swing.JPanel SetupTour;
    private javax.swing.JButton SetupTourButtton;
    private javax.swing.JComboBox<String> SportsComboBox;
    private javax.swing.JComboBox<String> SportsComboBox1;
    private javax.swing.JComboBox<String> SportsComboBox2;
    private javax.swing.JComboBox<String> SportsComboBox3;
    private javax.swing.JTabbedPane TabbedPanel;
    private javax.swing.JLabel Team1Label;
    private javax.swing.JLabel Team1Label1;
    private javax.swing.JScrollPane Team1ScrollPane1;
    private javax.swing.JLabel Team2Label;
    private javax.swing.JLabel Team2Label1;
    private javax.swing.JScrollPane Team2ScrollPane1;
    private javax.swing.JLabel TournamentTree;
    private javax.swing.JLabel TournamentTree3;
    private javax.swing.JPanel ViewGame;
    private javax.swing.JPanel ViewTour;
    private javax.swing.JButton ViewTourButtton;
    private javax.swing.JButton ViewTourButtton1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    // End of variables declaration//GEN-END:variables
}
